/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/renderer/index.html', './src/renderer/src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'nova-bg': 'var(--nova-bg)',
        'nova-bg-secondary': 'var(--nova-bg-secondary)',
        'nova-bg-tertiary': 'var(--nova-bg-tertiary)',
        'nova-sidebar': 'var(--nova-sidebar)',
        'nova-activitybar': 'var(--nova-activitybar)',
        'nova-titlebar': 'var(--nova-titlebar)',
        'nova-tab-active': 'var(--nova-tab-active)',
        'nova-tab-inactive': 'var(--nova-tab-inactive)',
        'nova-border': 'var(--nova-border)',
        'nova-text': 'var(--nova-text)',
        'nova-text-secondary': 'var(--nova-text-secondary)',
        'nova-text-muted': 'var(--nova-text-muted)',
        'nova-accent': 'var(--nova-accent)',
        'nova-accent-hover': 'var(--nova-accent-hover)',
        'nova-hover': 'var(--nova-hover)',
        'nova-scrollbar': 'var(--nova-scrollbar)',
        'nova-scrollbar-hover': 'var(--nova-scrollbar-hover)',
        'nova-terminal-bg': 'var(--nova-terminal-bg)',
        'nova-input-bg': 'var(--nova-input-bg)',
        'nova-input-border': 'var(--nova-input-border)',
        'nova-badge': 'var(--nova-badge)',
        'nova-error': 'var(--nova-error)',
        'nova-warning': 'var(--nova-warning)',
        'nova-info': 'var(--nova-info)',
        'nova-success': 'var(--nova-success)',
        'nova-highlight': 'var(--nova-highlight)',
        'nova-selection': 'var(--nova-selection)',
      },
      fontFamily: {
        mono: ['Geist Mono', 'Cascadia Code', 'Fira Code', 'JetBrains Mono', 'Consolas', 'monospace'],
        sans: ['Geist', 'Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
      },
      fontSize: {
        'tabs': '13px',
        'explorer': '13px',
        'status': '12px',
        'title': '12px',
        'editor': '14px',
        'terminal': '14px',
      },
      spacing: {
        'activity': '50px',
        'sidebar': '260px',
        'titlebar': '35px',
        'statusbar': '22px',
        'tab': '35px',
      },
    },
  },
  plugins: [],
}
