import { ipcMain, dialog, BrowserWindow } from 'electron'
import * as fs from 'fs'
import * as path from 'path'
import * as os from 'os'
import { execSync } from 'child_process'

const EXT_CHANNELS = {
  GENERATE_EXTENSION: 'extbuilder:generate-extension',
  GET_PAGE_ELEMENTS: 'extbuilder:get-page-elements',
  EXECUTE_IN_WEBVIEW: 'extbuilder:execute-in-webview',
}

export function registerExtensionBuilderHandlers(): void {
  // Generate Chrome extension files in a temp directory
  ipcMain.handle(EXT_CHANNELS.GENERATE_EXTENSION, async (_event, data: {
    name: string
    description: string
    targetUrl: string
    contentScript: string
    modifications: Array<{ type: string; selector: string; description: string; code: string }>
  }) => {
    try {
      const extName = data.name.replace(/[^a-zA-Z0-9_-]/g, '_').slice(0, 40) || 'ezek_extension'
      const tmpDir = path.join(os.tmpdir(), `ezek-ext-${extName}-${Date.now()}`)
      fs.mkdirSync(tmpDir, { recursive: true })

      // Build match pattern from target URL
      let matchPattern = '*://*/*'
      try {
        const url = new URL(data.targetUrl)
        matchPattern = `${url.protocol}//${url.hostname}/*`
      } catch {}

      // manifest.json
      const manifest = {
        manifest_version: 3,
        name: data.name || 'Ezek Custom Extension',
        version: '1.0.0',
        description: data.description || 'Extension generated by Ezek Editor Extension Builder',
        content_scripts: [{
          matches: [matchPattern],
          js: ['content.js'],
          run_at: 'document_end',
        }],
        host_permissions: [matchPattern],
        icons: {
          16: 'icon16.png',
          48: 'icon48.png',
          128: 'icon128.png',
        },
      }

      fs.writeFileSync(path.join(tmpDir, 'manifest.json'), JSON.stringify(manifest, null, 2))

      // content.js
      const contentScript = data.contentScript || buildFallbackScript(data.modifications)
      fs.writeFileSync(path.join(tmpDir, 'content.js'), contentScript)

      // Generate simple icons (1x1 PNG placeholder)
      const tinyPngBase64 = 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAAbwAAAG8B8aLcQwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAEVSURBVDiNpZMxTsNAEEX/rNeOQQIkGip8DURBQcnCIaB1fAIKbsAZaPIdfAQKroCkSJEiRUqUKGHXsZMQQoq1u56Z/W9nV8YYYso41g/D0Nj9/SrkMspzxu9mryrA2BsTALMsS+M47sMVSuk5pXSjlFoB/FBV5d47mAO6rhsmsBNCrJVSa+BnzrkA9jUAI4QY0zMPIdwVRXEPGDSlHCMiui7gPCIS0QcAVGs9RkQc4UQCCO9erYOD15QeANBat+CV0loLIt6EEH6Cb3dzEiDiCSJeE/EHcPZa4P3n+vQYQoy36V1yJdlHxGNKqRERfxCxIiKN1tqAj2vgl/7kB0CvtS689yc/Aa31yy+PYwwxHnP2QWu9AeAnCfiNEAWEMNSWAAACEklEQVQYV2Ng+M/AgBswMjD8Z2Bg+MfAwPCXgYHhLwMDw18GBoa/DAwM/xgYGPgZGBj4GBgY+BkYGPiYmBj5mBgZ+ZgYGfmYmBj5mJgY+ZiYGPmYmRj5WJgZ+VhYGPnYWBj5//1neMDAwMDAzc3N8O3bN/2srKzGv3//Mnz69Inhx48fDM+fP2f4/fv3MwUFhV0sLCx3/jMwMDCwsbHx6evrq7CysjJcvHjxDgMDAwMzMzMDHx8fAzs7OwMbGxsDBwcHAz8/PwMfHx8DHx8fg6CgIMPLly8Zvn//zvDt27db//793cPAwMCAEnNMTAzPTp36/6yl5f/v9ev//9++/T9DU9P//3p6/5mlJf+/VpD7/0BN7f87ba3/rzU1/3/S0f6vu2XLfw4Ghh0Kjoz/px1gRMgqMzH+Z2Ri/M/IwsjIwMbE9O+Wqtr/h0eP/mc4ceI/Aw8Pw39eXoZv3Dz/H/Hy/7/w/j3De2am//+fPfv/7sq1//8/ffr/7+On/yI7dvz/zcDA8J+BgeEfAwMDAwMjIyMDAwsjM8O3cxv+M5Ay8qoOfqfP3n0MKvo6DH9//mDQM9Jn9rDQuwbM8I+BgeEfAwMDAwMDA8MLBgYGPgYGBj4GBgY+BgYGPiYmRj4mJkY+JiZGPiYmRj4mJkY+JmYmPhYWZj4WFmY+FhZmPlZWZj5WVhY+VlYWPlZWZj4WFmY+VlYWPlY2Vj5WNrZ/Dg4O/4OCgv8LCgn95xfg/8/FzfWfk4uLMXBP/WMGEGBgYAAEAOkISX+Q2dALAAAAAElFTkSuQmCC'
      for (const size of [16, 48, 128]) {
        fs.writeFileSync(path.join(tmpDir, `icon${size}.png`), Buffer.from(tinyPngBase64, 'base64'))
      }

      // Try to create a zip using PowerShell
      const zipPath = path.join(os.tmpdir(), `${extName}.zip`)
      try {
        execSync(`powershell -NoProfile -Command "Compress-Archive -Path '${tmpDir}\\*' -DestinationPath '${zipPath}' -Force"`, { timeout: 10000 })
      } catch {
        // If zip fails, the folder is still usable
      }

      return {
        success: true,
        folderPath: tmpDir,
        zipPath: fs.existsSync(zipPath) ? zipPath : null,
        manifest,
        files: fs.readdirSync(tmpDir),
      }
    } catch (err: any) {
      return { success: false, error: err.message }
    }
  })

  // Open the extension folder in file explorer
  ipcMain.handle('extbuilder:open-folder', async (_event, folderPath: string) => {
    try {
      execSync(`explorer "${folderPath}"`)
      return { success: true }
    } catch (err: any) {
      return { success: false, error: err.message }
    }
  })

  // Save extension to user-chosen directory
  ipcMain.handle('extbuilder:save-extension', async (_event, data: {
    name: string
    description: string
    targetUrl: string
    contentScript: string
    modifications: Array<{ type: string; selector: string; description: string; code: string }>
  }) => {
    try {
      const win = BrowserWindow.getFocusedWindow()
      if (!win) return { success: false, error: 'No window' }

      const result = await dialog.showOpenDialog(win, {
        title: 'Escolha a pasta para salvar a extensão',
        properties: ['openDirectory', 'createDirectory'],
      })

      if (result.canceled || !result.filePaths[0]) return { success: false, error: 'Cancelado' }

      const extName = data.name.replace(/[^a-zA-Z0-9_-]/g, '_').slice(0, 40) || 'ezek_extension'
      const destDir = path.join(result.filePaths[0], extName)
      fs.mkdirSync(destDir, { recursive: true })

      let matchPattern = '*://*/*'
      try {
        const url = new URL(data.targetUrl)
        matchPattern = `${url.protocol}//${url.hostname}/*`
      } catch {}

      const manifest = {
        manifest_version: 3,
        name: data.name || 'Ezek Custom Extension',
        version: '1.0.0',
        description: data.description || 'Extension generated by Ezek Editor',
        content_scripts: [{
          matches: [matchPattern],
          js: ['content.js'],
          run_at: 'document_end',
        }],
        host_permissions: [matchPattern],
      }

      fs.writeFileSync(path.join(destDir, 'manifest.json'), JSON.stringify(manifest, null, 2))
      fs.writeFileSync(path.join(destDir, 'content.js'), data.contentScript || buildFallbackScript(data.modifications))

      return { success: true, folderPath: destDir }
    } catch (err: any) {
      return { success: false, error: err.message }
    }
  })
}

function buildFallbackScript(modifications: Array<{ type: string; selector: string; description: string; code?: string }>): string {
  const codes = modifications
    .filter((m) => m.code && m.code.trim())
    .map((m) => `  // ${m.type}: ${m.description}\n  ${m.code}`)

  return `// Ezek Extension Builder - Content Script
(function() {
  'use strict';
  console.log('[Ezek Extension] Loaded');
  
  function init() {
${codes.join('\n\n') || '    console.log("[Ezek Extension] No modifications defined yet.");'}
  }
  
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
`
}
